//------------------------------------------------------------------------
// Copyright(c) 2024 Baltis
// 
// 
// 
// 
// 
// 
// 
// .
//------------------------------------------------------------------------

#pragma once

#include "pluginterfaces/base/fplatform.h"

// Plain project version file generated by cmake 
#include "projectversion.h"

#define stringOriginalFilename	"BaltiReverb.vst3"
#if SMTG_PLATFORM_64
#define stringFileDescription	"BaltiFuzz VST3 (64Bit)"
#else
#define stringFileDescription	"BaltiFuzz VST3"
#endif
#define stringCompanyName		"BaltisFuzz\0"
#define stringLegalCopyright	"Copyright(c) 2024 BaltisFuzz."
#define stringLegalTrademarks	"VST is a trademark of Steinberg Media Technologies GmbH"
